In [1]:
from sklearn.datasets import load_iris
import numpy as np

iris = load_iris()
X = iris.data

variance_np = np.var(X,axis=0,ddof=1)
covariance_np = np.cov(X, rowvar=False)
correlation_np = np.corrcoef(X, rowvar=False)

print("Variance :",variance_np)
print("CoVariance :",covariance_np)
print("Correlation :",correlation_np)

Variance : [0.68569351 0.18997942 3.11627785 0.58100626]
CoVariance : [[ 0.68569351 -0.042434    1.27431544  0.51627069]
 [-0.042434    0.18997942 -0.32965638 -0.12163937]
 [ 1.27431544 -0.32965638  3.11627785  1.2956094 ]
 [ 0.51627069 -0.12163937  1.2956094   0.58100626]]
Correlation : [[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]
